version: 2.1

executors:
  ruby-executor:
    docker:
      - image: cimg/ruby:3.3.3
    working_directory: ~/repo

jobs:
  rspec:
    executor: ruby-executor
    steps:
      - checkout

      - run:
          name: Install Bundler
          command: gem install bundler -v 2.6.8

      - run:
          name: Bundle install
          command: bundle install --jobs=4

      - run:
          name: Run RSpec
          command: bundle exec rspec

workflows:
  version: 2
  run-tests:
    jobs:
      - rspec
